var love = 100;
console.log(love);
var name ="fahim";
console.log(name);
var yes = "@";
console.log(typeof yes);
var number = "4+6";
console.log( number);
var hello ="i love u too";
console.log(hello);
var hello ='i love my mom';
console.log(hello.indexOf('my'));
